---
{{- range .Values.databases }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  serviceName: "{{ .name }}"
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: {{ .image }}
        ports:
        - containerPort: {{ .port | default 5432 }}
        env:
        {{- if eq .type "postgresql" }}
        - name: POSTGRES_DB
          value: {{ .env.POSTGRES_DB }}
        - name: POSTGRES_USER
          value: {{ .env.POSTGRES_USER }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .name }}-secret
              key: {{ .secretEnv.POSTGRES_PASSWORD }}
        {{- end }}
        {{- if eq .type "mysql" }}
        - name: MYSQL_DATABASE
          value: {{ .env.MYSQL_DATABASE }}
        - name: MYSQL_USER
          value: {{ .env.MYSQL_USER }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .name }}-secret
              key: {{ .secretEnv.MYSQL_PASSWORD }}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .name }}-secret
              key: {{ .secretEnv.MYSQL_ROOT_PASSWORD }}
        {{- end }}
        resources:
          requests:
            cpu: {{ .resources.requests.cpu }}
            memory: {{ .resources.requests.memory }}
          limits:
            cpu: {{ .resources.limits.cpu }}
            memory: {{ .resources.limits.memory }}
        volumeMounts:
        - name: data
          mountPath: {{ .dataPath | default "/var/lib/postgresql/data" }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .storageClass | default "standard" }}
      resources:
        requests:
          storage: {{ .storage | default "1Gi" }}
---
{{- end }}